add_newline = false
format = "$username$hostname$directory$git_branch$git_status$kubernetes$aws$gcloud$cmd_duration$line_break$status$character"
right_format = "$time"

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true

[hostname]
ssh_only = true
format = "[@$hostname](bold yellow) "

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold yellow"

[cmd_duration]
min_time = 1_000

[status]
disabled = false

[time]
disabled = false
format = "[$time](dimmed white)"
time_format = "%H:%M"
